### ISSUE TITLE
Maybe operator precedence errors

### ISSUE THREAD

**Issue by Sober7135** [Enna1/remniw#38]
# Cause
https://github.com/Enna1/remniw/blame/709c4c7fa0624a093ca12de565ef38aaa646c556/grammar/Remniw.g4#L44

# Reproduce
## source code
```
func main() int {
  var x int;
  x = 5 - 9 + 4;
  return 0;
}
```
## emited ir
```
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

@fmtstr = private unnamed_addr constant [5 x i8] c"%lli\00", align 1
@fmtstr.1 = private unnamed_addr constant [6 x i8] c"%lli\0A\00", align 1

define i64 @main() {
entry:
  %x = alloca i64, align 8
  store i64 -8, ptr %x, align 8
  ret i64 0
}
```
it should be 0 rather than -8. This is because `9 + 4` will be matched before `5 - 9` caused by the precedence of the grammar...
```
   | expr ('+' | '-')  expr # AddExpr
```
this may solve the problem.
~~I guess `*` and `/` have the same problem.~~

**Comment by Enna1** [comment]
Thanks for reporting this!
Will fix when I have time...
